blogTitle = "Schlackermaschü"
blogDescription = "A beautiful narrative written with the worlds most elegant publishing platform. The story begins here."
authorName = "Axinja Tannhäuser"
linkPrefix = ""
blogImage = "/static/img/cover.jpg"
twitter = "https://twitter.com/_axinja_"
email = "axinja.tannhaeuser@gmx.net"
gaTrackingCode = "trackingCode"